---
classes:
  - lab_resources:
      - display_name: "AWS EC2 Instance"
        platform_type: "lab"
        image_platform: "linux"
        view_interface: "desktop"
        cloud_provider: "aws"
        aws_vm_definition:
          machine_size: "t2.micro"
          ami_region_mapping:
            eu-west-1:
              image_id: "ami-0b32f4a77e48fcb24"
    exercises:
      - file: "../hello-world/hello.md"
        title: "Hello!"
